"""modify user model

Revision ID: 28612b39c709
Revises: 
Create Date: 2023-04-05 07:17:19.710670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28612b39c709'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('birth_year')

    # ### end Alembic commands ###
